version: '3.7'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itflow_apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/var/www/html
    networks:
      - itflow-network



  # Optional: Redis service for caching (if you want to use Redis)
  redis:
    image: redis:alpine
    container_name: itflow_redis
    networks:
      - itflow-network

volumes:
  mariadb_data:
    driver: local

networks:
  itflow-network:
    driver: bridge
