version: '3.8'

services:
  app:
    image: php:8.0-fpm
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini # Custom PHP configuration (optional)
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80" # Map port 8080 to the container's port 80
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
